package kiwi.orbit.compose.catalog.semantics

object MainScreenSemantics {
    const val Tag = "main_screen"

    const val ColorsItemTag = "main_screen_colors_item_item"
    const val IconsItemTag = "main_screen_icons_item"
    const val IllustrationsItemTag = "main_screen_illustrations_item"
    const val TypographyItemTag = "main_screen_typography_item"

    const val AlertItemTag = "main_screen_alert_item"
    const val BadgeItemTag = "main_screen_badge_item"
    const val BadgeListItemTag = "main_screen_badge_list_item"
    const val ButtonItemTag = "main_screen_button_item"
    const val CardItemTag = "main_screen_card_item"
    const val CheckboxItemTag = "main_screen_checkbox_item"
    const val ChoiceTileItemTag = "main_screen_choice_tile_item"
    const val CollapseItemTag = "main_screen_collapse_item"
    const val DialogItemTag = "main_screen_dialog_item"
    const val EmptyStateItemTag = "main_screen_empty_state_item"
    const val KeyValueItemTag = "main_screen_key_value_item"
    const val ListItemTag = "main_screen_list_item"
    const val ListChoiceItemTag = "main_screen_list_choice_item"
    const val LoadingItemTag = "main_screen_loading_item"
    const val PillButtonItemTag = "main_screen_pill_button_item"
    const val ProgressIndicatorItemTag = "main_screen_progress_indicator_item"
    const val RadioItemTag = "main_screen_radio_item"
    const val SeatItemTag = "main_screen_seat_item"
    const val SegmentedSwitchItemTag = "main_screen_segmented_switch_item"
    const val SelectFieldItemTag = "main_screen_select_field_item"
    const val SliderItemTag = "main_screen_slider_item"
    const val StepperItemTag = "main_screen_stepper_item"
    const val SurfaceCardItemTag = "main_screen_surface_card_item"
    const val SwitchItemTag = "main_screen_switch_item"
    const val TabsItemTag = "main_screen_tabs_item"
    const val TagItemTag = "main_screen_tag_item"
    const val TextFieldItemTag = "main_screen_text_field_item"
    const val TileItemTag = "main_screen_tile_item"
    const val TileGroupItemTag = "main_screen_tile_group_item"
    const val TimelineItemTag = "main_screen_timeline_item"
    const val ToastItemTag = "main_screen_toast_item"
    const val TopAppBarItemTag = "main_screen_top_app_bar_item"
}
